#!/usr/bin/env python3
"""
Run this script whenever you update data/starwars_content.json or
data/clone_wars_episodes.json to regenerate data.js.

Usage:
    python3 generate_data.py
"""
import json, os

base = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(base, 'data', 'starwars_content.json')) as f:
    content = json.load(f)

with open(os.path.join(base, 'data', 'clone_wars_episodes.json')) as f:
    cw = json.load(f)

with open(os.path.join(base, 'data', 'project_info.json')) as f:
    info = json.load(f)

out = f"""// AUTO-GENERATED by generate_data.py — do not edit manually.
// Edit the JSON files in data/ then re-run: python3 generate_data.py
const CONTENT_DATA = {json.dumps(content, separators=(',', ':'))};
const CW_DATA = {json.dumps(cw, separators=(',', ':'))};
const PROJECT_INFO = {json.dumps(info, separators=(',', ':'))};

// ─────────────────────────────────────────────────────────────────────────────
// HOW TO UPDATE CONTENT:
// 1. Edit data/starwars_content.json or data/clone_wars_episodes.json
// 2. Re-run: python3 generate_data.py
// ─────────────────────────────────────────────────────────────────────────────
"""

out_path = os.path.join(base, 'data.js')
with open(out_path, 'w') as f:
    f.write(out)

print(f"✓ data.js written ({len(out):,} bytes)")
