#!/usr/bin/env python3
"""
Run this script whenever you update any JSON in data/ to regenerate data.js.

Usage:
    python3 generate_data.py
"""
import json, os

base = os.path.dirname(os.path.abspath(__file__))

def load(filename):
    with open(os.path.join(base, 'data', filename)) as f:
        return json.load(f)

content  = load('starwars_content.json')
cw       = load('clone_wars_episodes.json')
rebels   = load('rebels_episodes.json')
res      = load('resistance_episodes.json')
mando    = load('mando_episodes.json')
bb       = load('bad_batch_episodes.json')
info     = load('project_info.json')

out = f"""// AUTO-GENERATED by generate_data.py — do not edit manually.
// Edit the JSON files in data/ then re-run: python3 generate_data.py
const CONTENT_DATA = {json.dumps(content, separators=(',', ':'))};
const CW_DATA = {json.dumps(cw, separators=(',', ':'))};
const REBELS_DATA = {json.dumps(rebels, separators=(',', ':'))};
const RESISTANCE_DATA = {json.dumps(res, separators=(',', ':'))};
const MANDO_DATA = {json.dumps(mando, separators=(',', ':'))};
const BAD_BATCH_DATA = {json.dumps(bb, separators=(',', ':'))};
const PROJECT_INFO = {json.dumps(info, separators=(',', ':'))};

// ─────────────────────────────────────────────────────────────────────────────
// HOW TO UPDATE CONTENT:
// 1. Edit any JSON file in data/
// 2. Re-run: python3 generate_data.py
// ─────────────────────────────────────────────────────────────────────────────
"""

out_path = os.path.join(base, 'data.js')
with open(out_path, 'w') as f:
    f.write(out)

print(f"✓ data.js written ({len(out):,} bytes)")
